# Generated by Django 3.1.5 on 2021-01-14 12:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dead_people',
            fields=[
                ('idDead_people', models.AutoField(primary_key=True, serialize=False)),
                ('Imie', models.CharField(max_length=15)),
                ('Nazwisko', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Nagrobki',
            fields=[
                ('idNagrobki', models.AutoField(primary_key=True, serialize=False)),
                ('Sektor', models.CharField(max_length=10)),
                ('Rzad', models.CharField(max_length=10)),
                ('Wiadomosc', models.CharField(max_length=60)),
                ('Dead_people_idDead_people', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.dead_people')),
            ],
        ),
    ]
