# Generated by Django 3.1.5 on 2021-01-16 12:25

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='dead_people',
            name='Data_smier',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='dead_people',
            name='Data_uro',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nagrobki',
            name='Miejsce_rzad',
            field=models.IntegerField(default=0),
        ),
    ]
