# Generated by Django 3.1.5 on 2021-02-01 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_auto_20210116_1325'),
    ]

    operations = [
        migrations.AlterField(
            model_name='nagrobki',
            name='Rzad',
            field=models.CharField(max_length=2),
        ),
        migrations.AlterField(
            model_name='nagrobki',
            name='Sektor',
            field=models.CharField(max_length=2),
        ),
    ]
