# Generated by Django 3.1.5 on 2021-02-02 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_auto_20210201_1740'),
    ]

    operations = [
        migrations.RenameField(
            model_name='nagrobki',
            old_name='Dead_people_idDead_people',
            new_name='dead_people',
        ),
        migrations.AddField(
            model_name='dead_people',
            name='gender',
            field=models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=2),
        ),
    ]
