# Generated by Django 3.1.5 on 2021-02-02 08:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_auto_20210202_0900'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dead_people',
            name='Data_smier',
            field=models.DateField(blank=True, null=True),
        ),
    ]
